# Generated by Django 3.2.9 on 2024-07-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=10)),
                ('servicio', models.CharField(choices=[('sin servicio', 'Sin Servicio'), ('con servicio', 'Con Servicio')], default='sin servicio', max_length=20)),
                ('visualizada', models.BooleanField(default=False)),
            ],
        ),
    ]
