# Generated by Django 3.2.9 on 2024-07-17 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cita', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cita.cita'),
        ),
    ]
