# Generated by Django 3.2.9 on 2024-07-17 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('servicio', '0001_initial'),
        ('car', '0002_cartitem_cita'),
        ('paciente', '0001_initial'),
        ('odontologo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio'),
        ),
        migrations.AddField(
            model_name='cart',
            name='idOdontologo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='odontologo.odontologo'),
        ),
        migrations.AddField(
            model_name='cart',
            name='idPaciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paciente.paciente'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
