# Generated by Django 3.2.9 on 2024-07-17 00:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('resized_image', models.ImageField(blank=True, null=True, upload_to='resized/')),
                ('mask', models.ImageField(blank=True, null=True, upload_to='masks/')),
                ('edited_images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(blank=True, max_length=500, null=True), blank=True, null=True, size=5)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
